/*
* generated by Xtext
*/
package org.xtext.ecerule;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EceUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.ecerule.ui.internal.EceActivator.getInstance().getInjector("org.xtext.ecerule.Ece");
	}
	
}
