package rec.dom
import java.util.concurrent.TimeUnit;
global org.drools.time.SessionPseudoClock clock;

declare LeftArmLowered// extends Sample
	value: double
end

rule "InTempDeclarations" 
when
then
	System.out.println("//Sono dentro a TempDeclarations.drl");
end

rule "Initially" 
when
then
	//insert(new AlzatoE((long)  0));  //evento arriva a tempo 0
	
	//clock.advanceTime(13, TimeUnit.MILLISECONDS);
	//insert(new SedutoF((double)0));  //valore del fluente
	//System.out.println("//Aggiunti fatti...");	
end



rule "test delay"  
when
	
$evPtr: LeftArmStretched($tsmp:time)
	LeftArmLowered($val_LeftArmLowered:value);
then
	System.out.println("delay= "+(clock.getCurrentTime()-$tsmp));
end




