package rec.dom;

global org.drools.time.SessionPseudoClock clock;

rule "Fulfilment 49153"
when
	
$evPtr: LeftArmStretched($tsmp:time)
	LeftArmLowered($val_LeftArmLowered:value);

	eval(($val_LeftArmLowered==0.0)==true && (clock.getCurrentTime()<$tsmp+10 && clock.getCurrentTime()>$tsmp)==true)
then
	System.out.println("FULFILLED :)");
end

rule "Violation 34637"
when
	
$evPtr: LeftArmStretched($tsmp:time)
	LeftArmLowered($val_LeftArmLowered:value);

	eval(($val_LeftArmLowered==0.0)==false || (clock.getCurrentTime()<$tsmp+10 && clock.getCurrentTime()>$tsmp)==false)
then
	System.out.println("VIOLATED :(");
end




rule "InSingleGenerated" 
when
then
	System.out.println("//Sono dentro a Expectations.drl");
end