/*
 * generated by Xtext
 */
package org.xtext.ecerule.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EceUiModule extends org.xtext.ecerule.ui.AbstractEceUiModule {
	public EceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
