/*
 * generated by Xtext
 */
package org.xtext.ecerule.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ecerule.ui.internal.EceActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EceActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EceActivator.getInstance().getInjector(EceActivator.ORG_XTEXT_ECERULE_ECE);
	}
	
}
