package com.sample
 
import org.xtext.ecerule.model.*;
 
 
rule "Success"
	when
		$stm: Statement()
		$expc: ExpContext() from $stm.expContextList
		ConditionInterface(this.validate()==true) from $expc.finalCondition
	then
		System.out.println("Success");
		//$stm.setSuccess();
		
end

rule "Failure"
	when
		$stm: Statement()
		$expc: ExpContext() from $stm.expContextList
		ConditionInterface(this.validate()==false) from $expc.finalCondition
	then
		System.out.println("Failure");
		//$stm.setFailure();
end
	 
