/*
* generated by Xtext
*/
package org.xtext.ecerule.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ecerule.services.EceGrammarAccess;

public class EceParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EceGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.ecerule.parser.antlr.internal.InternalEceParser createParser(XtextTokenStream stream) {
		return new org.xtext.ecerule.parser.antlr.internal.InternalEceParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EceModel";
	}
	
	public EceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
