/**
 * generated by Xtext
 */
package org.xtext.ecerule.validation;

import org.xtext.ecerule.validation.AbstractEceValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EceValidator extends AbstractEceValidator {
}
