/**
 * generated by Xtext
 */
package org.xtext.ecerule.ui.contentassist;

import org.xtext.ecerule.ui.contentassist.AbstractEceProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class EceProposalProvider extends AbstractEceProposalProvider {
}
