package rec.dom;

global org.drools.time.SessionPseudoClock clock;

rule "Fulfilment 22369"
when
	
$evPtr: AlzatoE($tsmp:time)
	SedutoF($val_SedutoF:value);

	eval(($val_SedutoF==0.0)==true && ($tsmp<clock.getCurrentTime()-10)==true)
then
	System.out.println("FULFILLED :)");
end

rule "Violation 20550"
when
	
$evPtr: AlzatoE($tsmp:time)
	SedutoF($val_SedutoF:value);

	eval(($val_SedutoF==0.0)==false || ($tsmp<clock.getCurrentTime()-10)==false)
then
	System.out.println("VIOLATED :(");
end


rule "InSingleGenerated" 
when
then
	System.out.println("Sono dentro a SingleGenerated.drl");
end