//created on: 14-nov-2013
package com.rules.generationrules



rule "Expectation - SiAlza"
when
$evnow: EventNow(this.getEventName().equals("SiAlza"), $et: this.getExpeTimeFC())
then 
insert(new Expectation(org.xtext.ecerule.model.conditions.relations.SameDescr@6460efa5, $et+10.0));
end


rule "Expectation - SiAlza"
when
$evnow: EventNow(this.getEventName().equals("SiAlza"), $et: this.getExpeTimeFC())
then
insert(new Expectation(org.xtext.ecerule.model.conditions.relations.SameDescr@6460efa5, $et+10.0));
end


rule "Expectation - SiAlza"
when
$evnow: EventNow(this.getEventName().equals("SiAlza"), $et: this.getExpeTimeFC())
then
insert(new Expectation(org.xtext.ecerule.model.conditions.relations.SameDescr@4f1b5c27, $et+10.0));
end


rule "Expectation - SiAlza"
when
$evnow: EventNow(this.getEventName().equals("SiAlza"), $et: this.getExpeTimeFC())
then
insert(new Expectation(org.xtext.ecerule.model.conditions.relations.SameDescr@2ea46867, $et+10.0));
end


rule "Expectation - SiAlza"
when
$evnow: EventNow(this.getEventName().equals("SiAlza"), $et: this.getExpeTimeFC())
then
insert(new Expectation(org.xtext.ecerule.model.conditions.relations.SameDescr@31f9bcbc, $et+10.0));
end


rule "Expectation - SiAlza"
when
$evnow: EventNow(this.getEventName().equals("SiAlza"), $et: this.getExpeTimeFC())
then
insert(new Expectation(org.xtext.ecerule.model.conditions.relations.SameDescr@31f9bcbc, $et+10.0));
end


rule "Expectation - SiAlza"
when
$evnow: EventNow(this.getEventName().equals("SiAlza"), $et: this.getExpeTimeFC())
then
insert(new Expectation(org.xtext.ecerule.model.conditions.relations.SameDescr@1fe0a337, $et+10.0));
end
