//created on: 14-nov-2013
package com.rules.generationrules

//list any import classes here.
import org.xtext.ecerule.model.*;
import java.io.*;

rule "Parse Statements"

    when
    	$stm: Statement($ctxl: this.getExpContextList())
    	$ev: Event($evn: this.getEventName()) from $stm.event
    	$expc: ExpContext($fc: this.getFinalCondition(), $rit: this.getTime().getTimeValue()) from $ctxl
      
    then
    
    	System.out.println("1-sono entrato nel then");
    	//generazione codice .drl
    	
    	String path= "src/main/rules/com/rules/generationrules/DynamicRules.drl";
        PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(path, true)));
        out.println();
        out.println();
        
        
        out.println("rule \"Expectation - "+$evn+"\"");
        out.println("when");
        
        	out.println("$evnow: EventNow(this.getEventName().equals(\""+$evn+"\"), $et: this.getExpeTimeFC())");
       
        out.println("then");
        
        	out.println("insert(new Expectation("+$fc+", $et+"+$rit+"));");
        
        out.println("end");
        
        
        
        
        out.close();
      	
end

