//created on: 14-nov-2013
package com.rules.generationrules

//list any import classes here.
import com.rules.generationrules.*


//declare any global variables here




rule "Success Rule"

    when
    	$clk:Clock($clkt:this.getTimeStamp())
        $exp: Expectation(this.getFinalCondition().validate()==true, this.getExpeTimeFC()==$clkt)
    then
        $exp.setSuccess();
        retract ($clk);

end

rule "failure Rule"

    when
    	$clk:Clock($clkt:this.getTimeStamp())
        $exp: Expectation(this.getFinalCondition().validate()==false, this.getExpeTimeFC()==$clkt)
    then
        $exp.setFailure();
        retract ($clk);

end
