package com.sample.twosteps

declare Expectation
	event: String
	finCond: String
	codeViol: String
	codeFulf: String
	codeViol: String
end

rule "RuotaTestaSX 46551"
when
then
	insert(new Expectation("RuotaTestaSX", "TestaRuotataDX==true after 10", "<code if fulfilled>", "<code if violated>"));
	System.out.println("Generate Expectation - RuotaTestaSX");
end


rule "SiDistende 87262"
when
then
	insert(new Expectation("SiDistende", "Inginocchiato==true after 10", "<code if fulfilled>", "<code if violated>"));
	System.out.println("Generate Expectation - SiDistende");
end


rule "SiAlza 59203"
when
then
	insert(new Expectation("SiAlza", "Alzato==true after 10", "<code if fulfilled>", "<code if violated>"));
	System.out.println("Generate Expectation - SiAlza");
end


