/*
 * generated by Xtext
 */
package org.xtext.ecerule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EceRuntimeModule extends org.xtext.ecerule.AbstractEceRuntimeModule {

}
